In [4]:
import numpy as np

In [5]:
np.__version__

'1.23.5'

In [6]:
list = ["Home", "Alone"]
arr = np.array(list)
arr

array(['Home', 'Alone'], dtype='<U5')

In [7]:
type(arr)

numpy.ndarray

In [10]:
arr = np.array((3, 34, 23, 9, 3))
arr

array([ 3, 34, 23,  9,  3])

In [15]:
np.array([[[3, 23], [23, 32]], [34, 23], [23, 3]], dtype=object)

array([[list([3, 23]), list([23, 32])],
       [34, 23],
       [23, 3]], dtype=object)

In [16]:
np.array([32, 23, 23])

array([32, 23, 23])

In [20]:
np.array([[23, 23, True], [32, 23, "Home"]], dtype=object)

array([[23, 23, True],
       [32, 23, 'Home']], dtype=object)

In [21]:
np.array([32, 9, "Homecomming", True, 9.2])

array(['32', '9', 'Homecomming', 'True', '9.2'], dtype='<U32')

# Data science

How it install library in google collab
```python
    !pip install library_name
```

In [22]:
!pip install numpy

# Importing Numpy

In [23]:
import numpy as np

# Creating an empty array

In [25]:
x = np.array([])
type(x)

numpy.ndarray

In [26]:
x

array([], dtype=float64)

# Creating an array with even numbers

In [28]:
even = [2, 4, 6, 2, 98, 22]

In [29]:
even_array = np.array(even)

In [30]:
even_array

array([ 2,  4,  6,  2, 98, 22])

In [31]:
type(even_array)

numpy.ndarray

In [32]:
# nd means n-dimensional

In [34]:
even_array.ndim # ndim gives no of dimensions; this is 1 dimensional array

1

In [35]:
even_array.shape # (length_of_array, )

(6,)

In [36]:
len(even_array)

6

# Indexing and slicing

In [41]:
x = np.array([243, 232, 211, 454, 198, 399])

In [42]:
x

array([243, 232, 211, 454, 198, 399])

In [43]:
x[3]

454

In [44]:
x[-2]

198

In [45]:
x[2:5]

array([211, 454, 198])

In [48]:
x[2:-2] # slicing

array([211, 454])

In [49]:
x[:4]

array([243, 232, 211, 454])

In [50]:
x[-4:]

array([211, 454, 198, 399])

# Difference between list and array
* Array operation are faster than list operation which means array is faster then list
* List supports mutiple data types in contrast array support homogenous data type
* Array are memory effecient than list

# data type

In [54]:
l1 = [True, "hello", 55, 34.2]
type(l1[0])

bool

In [55]:
l1_array = np.array(l1)
l1_array

array(['True', 'hello', '55', '34.2'], dtype='<U32')

In [56]:
type(l1_array[0])

numpy.str_

# Random number generation

In [59]:
np.random.randint(1, 10)

4

In [65]:
np.random.seed(0)
np.random.randint(1, 10)

6

In [66]:
x_array = np.random.randint(low=1, high=10, size=50000)
x_array

array([1, 4, 4, ..., 9, 5, 2])

In [67]:
len(x_array)

50000

In [68]:
x_list = x_array.tolist() # typecasting array to list

In [69]:
type(x_list)

list

In [ ]:
x_list

In [77]:
%%time
sq = [item ** 2 for item in x_list] # list operation

CPU times: user 14.2 ms, sys: 0 ns, total: 14.2 ms
Wall time: 14.7 ms


In [76]:
%%time
sq = x_array ** 2 # array operation

CPU times: user 707 µs, sys: 0 ns, total: 707 µs
Wall time: 591 µs
