In [ ]:
import numpy as np

In [ ]:
np.__version__

'1.25.2'

In [ ]:
list = ["Home", "Alone"]
arr = np.array(list)
arr

array(['Home', 'Alone'], dtype='<U5')

In [ ]:
type(arr)

numpy.ndarray

In [ ]:
arr = np.array((3, 34, 23, 9, 3))
arr

array([ 3, 34, 23,  9,  3])

In [ ]:
np.array([[[3, 23], [23, 32]], [34, 23], [23, 3]], dtype=object)

array([[list([3, 23]), list([23, 32])],
       [34, 23],
       [23, 3]], dtype=object)

In [ ]:
np.array([32, 23, 23])

array([32, 23, 23])

In [ ]:
np.array([[23, 23, True], [32, 23, "Home"]], dtype=object)

array([[23, 23, True],
       [32, 23, 'Home']], dtype=object)

In [ ]:
np.array([32, 9, "Homecomming", True, 9.2])

array(['32', '9', 'Homecomming', 'True', '9.2'], dtype='<U32')

# Data science

How it install library in google collab
```python
    !pip install library_name
```

In [ ]:
!pip install numpy

# Importing Numpy

In [ ]:
import numpy as np

# Creating an empty array

In [ ]:
x = np.array([])
type(x)

numpy.ndarray

In [ ]:
x

array([], dtype=float64)

# Creating an array with even numbers

In [ ]:
even = [2, 4, 6, 2, 98, 22]

In [ ]:
even_array = np.array(even)

In [ ]:
even_array

array([ 2,  4,  6,  2, 98, 22])

In [ ]:
type(even_array)

numpy.ndarray

In [ ]:
# nd means n-dimensional

In [ ]:
even_array.ndim # ndim gives no of dimensions; this is 1 dimensional array

1

In [ ]:
even_array.shape # (length_of_array, )

(6,)

In [ ]:
len(even_array)

6

# Indexing and slicing

In [ ]:
x = np.array([243, 232, 211, 454, 198, 399])

In [ ]:
x

array([243, 232, 211, 454, 198, 399])

In [ ]:
x[3]

454

In [ ]:
x[-2]

198

In [ ]:
x[2:5]

array([211, 454, 198])

In [ ]:
x[2:-2] # slicing

array([211, 454])

In [ ]:
x[:4]

array([243, 232, 211, 454])

In [ ]:
x[-4:]

array([211, 454, 198, 399])

# Difference between list and array
* Array operation are faster than list operation which means array is faster then list
* List supports mutiple data types in contrast array support homogenous data type
* Array are memory effecient than list

# data type

In [ ]:
l1 = [True, "hello", 55, 34.2]
type(l1[0])

bool

In [ ]:
l1_array = np.array(l1)
l1_array

array(['True', 'hello', '55', '34.2'], dtype='<U32')

In [ ]:
type(l1_array[0])

numpy.str_

# Random number generation

In [ ]:
np.random.randint(1, 10)

5

In [ ]:
np.random.seed(0)
np.random.randint(1, 10)

6

In [ ]:
x_array = np.random.randint(low=1, high=10, size=50000)
x_array

array([1, 4, 4, ..., 9, 5, 2])

In [ ]:
len(x_array)

50000

In [ ]:
x_list = x_array.tolist() # typecasting array to list

In [ ]:
type(x_list)

list

In [ ]:
%%time
sq = [item ** 2 for item in x_list] # list operation

CPU times: user 15.4 ms, sys: 1.13 ms, total: 16.6 ms
Wall time: 21.3 ms


In [ ]:
%%time
sq = x_array ** 2 # array operation

CPU times: user 376 µs, sys: 0 ns, total: 376 µs
Wall time: 382 µs


# array is memory efficient

In [ ]:
import numpy as np

In [ ]:
even = np.array([95, 6, 2, 100], dtype = np.int8)
even

array([ 95,   6,   2, 100], dtype=int8)

In [ ]:
even = np.array([95, 6, 2, 100], dtype = np.int16)
even

array([ 95,   6,   2, 100], dtype=int16)

# zeros(), ones() and empty()

In [ ]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [ ]:
np.ones(3, dtype=np.int8)

array([1, 1, 1], dtype=int8)

In [ ]:
np.empty(15) # empty depends on memory

array([4.85620433e-310, 0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
       0.00000000e+000, 1.50008929e+248, 4.31174539e-096, 9.80058441e+252,
       1.23971686e+224, 1.05191791e-153, 9.03292329e+271, 9.08366793e+223,
       1.06244660e-153, 3.44981369e+175, 6.32404027e-322])

In [ ]:
# zeros and ones are used in binary image masking

# .arange()

In [ ]:
np.arange(start=0, stop=5, step=1)

array([0, 1, 2, 3, 4])

In [ ]:
# b = (range(1, 19, 2))
# list(b)

# .linspace()

In [ ]:
np.linspace(start=0, stop=1, num=5) #0.25 is equal spacing

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [ ]:
# zero dekhi one samma 5 number generate garne with equal spacing

# sort() and concatinate()

In [ ]:
x = np.array([5, 0, -2, 6, 1, 9, 5])

In [ ]:
np.sort(x) # ascendcing

array([-2,  0,  1,  5,  5,  6,  9])

In [ ]:
np.flip(np.sort(x)) # descending

array([ 9,  6,  5,  5,  1,  0, -2])

In [ ]:
x[::-1]

array([ 5,  9,  1,  6, -2,  0,  5])

In [ ]:
x = np.array([5, 6])
y = np.array([1, 2, 3])

In [ ]:
[5, 3] + [1, 2, 3] # you can concatinate list using + operator

[5, 3, 1, 2, 3]

In [ ]:
# x + y # array can't concatinate like this

In [ ]:
np.concatenate([x, y])

array([5, 6, 1, 2, 3])

# Vector operations and Broadcasting

In [ ]:
# vector operations
x = np.array([8, 9])
y = np.array([2, 3])

In [ ]:
x + y

array([10, 12])

In [ ]:
x - y

array([6, 6])

In [ ]:
x * y

array([16, 27])

In [ ]:
x / y

array([4., 3.])

In [ ]:
x % y

array([0, 0])

In [ ]:
# broadcasting
x = np.array([8, 9])
y = np.array([2, 3])
2 * x
2 * y

array([4, 6])

In [ ]:
3 + x

array([11, 12])

In [ ]:
3 - y

array([1, 0])

In [ ]:
5 - x

array([-3, -4])

# .any() vs .all()

In [ ]:
np.random.seed()
x = np.random.randint(1, 7, 10) # low, high, size
x

array([4, 4, 3, 3, 3, 1, 3, 3, 5, 2])

In [ ]:
x >= 5

array([False, False, False, False, False, False, False, False,  True,
       False])

In [ ]:
np.any(x>=5) # kunai 5 vanda thulo xa vane True aauxa

True

In [ ]:
np.all(x>=5) # sabai 5 vanda thulo vayo vane True natra False

False

In [ ]:
np.all(x>=5)

False

In [ ]:
x[x>=5]

array([5])

In [ ]:
# x[x==1 or x==6] # logical operator numpy ma use garna paudaina

# numpy works in bitwise operator

In [ ]:
x[(x==1) | (x==6)] # bitwise or

array([1])

In [ ]:
x[(x > 2) & (x < 6)] # bitwise and

array([4, 4, 3, 3, 3, 3, 3, 5])

# statistics using numpy

In [ ]:
np.random.seed(0)
x = np.random.randint(1, 100, size=50)
x

array([45, 48, 65, 68, 68, 10, 84, 22, 37, 88, 71, 89, 89, 13, 59, 66, 40,
       88, 47, 89, 82, 38, 26, 78, 73, 10, 21, 81, 70, 80, 48, 65, 83, 89,
       50, 30, 20, 20, 15, 40, 33, 66, 10, 58, 33, 32, 75, 24, 36, 76])

In [ ]:
np.mean(x)

52.96

In [ ]:
x.mean()

52.96

In [ ]:
np.median(x)

54.0

In [ ]:
np.var(x) # variance

659.9584

In [ ]:
np.std(x) # standard deviation

25.689655505669982

In [ ]:
np.min(x)

10

In [ ]:
np.max(x)

89

In [ ]:
from scipy.stats import mode
mode(x)

ModeResult(mode=89, count=4)

In [ ]:
np.argmax(x)

11

In [ ]:
np.argmin(x)

5

# 2D array

In [ ]:
import numpy as np

In [ ]:
matrix = np.array( [ [1, 3, 2], [4, 5, 6], [7, 9, 8] ] )

In [ ]:
matrix

array([[1, 3, 2],
       [4, 5, 6],
       [7, 9, 9]])

In [ ]:
matrix.ndim

2

In [ ]:
matrix.shape

(3, 3)

In [ ]:
arr = np.array(["Home", True, 9, 2.8], dtype="object")

In [ ]:
arr

array(['Home', True, 9, 2.8], dtype=object)

In [ ]:
type(arr[1])

bool

# indexing and slicing 2d matrix

# indexing

In [ ]:
matrix = np.array( [ [1, 3, 2], [4, 5, 6], [7, 9, 8] ] )

In [ ]:
matrix.shape

(3, 3)

In [ ]:
matrix[1, 1]

5

In [ ]:
matrix[1,2]

6

In [ ]:
matrix[0, 1]

3

In [ ]:
matrix[2, 2]

8

In [ ]:
matrix[1, 2]

6

In [ ]:
matrix[1, 0]

4

# Slicing

In [ ]:
matrix = np.array( [ [1, 3, 2], [4, 5, 6], [7, 9, 8] ] )

In [ ]:
matrix[:, 2]

array([2, 6, 8])

In [ ]:
matrix[:, 0]

array([1, 4, 7])

In [ ]:
matrix[1, :]

array([4, 5, 6])

In [ ]:
matrix[2, :]

array([7, 9, 8])

In [ ]:
matrix[1:, 1:]

array([[5, 6],
       [9, 8]])

In [ ]:
matrix[:2, :2]

array([[1, 3],
       [4, 5]])

In [ ]:
matrix[:2, 1:]

array([[3, 2],
       [5, 6]])

In [ ]:
matrix

array([[1, 3, 2],
       [4, 5, 6],
       [7, 9, 8]])

In [ ]:
matrix[1:, :2]

array([[4, 5],
       [7, 9]])

In [ ]:
matrix[1:, 1:]

array([[5, 6],
       [9, 8]])

In [ ]:
matrix[:2, 1:]

array([[3, 2],
       [5, 6]])

In [ ]:
matrix

array([[1, 3, 2],
       [4, 5, 6],
       [7, 9, 8]])

In [ ]:
matrix[1:, 1:]

array([[5, 6],
       [9, 8]])

# Matrix operations

Dot product, Matrix multiplicaiton - linear algebra

In [ ]:
A = np.array( [[1, 2, 3], [4, 5, 6]] )
B = np.array([[7, 8], [9, 10], [11, 12]])

In [ ]:
A.shape

(2, 3)

In [ ]:
B.shape

(3, 2)

In [ ]:
output = np.dot(A, B)

In [ ]:
output

array([[ 58,  64],
       [139, 154]])

In [ ]:
np.linalg.det(output)

36.000000000000256

In [ ]:
np.round(np.linalg.det(output), 2)

36.0

In [ ]:
np.round(234.2343, 2)

234.23

In [ ]:
np.floor(5.34)

5.0

In [ ]:
np.ceil(23.653)

24.0

In [ ]:
np.linalg.inv(output)

array([[ 4.27777778, -1.77777778],
       [-3.86111111,  1.61111111]])

# The axis argument in numpy: 2D axis = 0 is column-wise and axis = 1 means row-wise.

In [ ]:
matrix = np.array([[4, 5, 6], [7, 9, 8]])
matrix.shape

(2, 3)

In [ ]:
matrix

array([[4, 5, 6],
       [7, 9, 8]])

In [ ]:
matrix.sum() # 4 + 5 + 6 + 7 + 9 + 8

39

In [ ]:
matrix.sum(axis=0) # vertically

array([11, 14, 14])

In [ ]:
matrix.sum(axis=1) # horizontally

array([15, 24])

# .flatten()

In [ ]:
matrix = np.array([[4, 5, 6], [7, 9, 8]])
matrix # 2D

array([[4, 5, 6],
       [7, 9, 8]])

In [ ]:
matrix.flatten() # 1D

array([4, 5, 6, 7, 9, 8])

# .reshape()

In [ ]:
x = np.array(np.random.randint(2, 8, 6))

In [ ]:
x

array([7, 7, 2, 6, 3, 6])

In [ ]:
x.ndim

1

In [ ]:
x.reshape(2, 3)

array([[7, 7, 2],
       [6, 3, 6]])

In [ ]:
x.reshape(3, 2)

array([[7, 7],
       [2, 6],
       [3, 6]])

In [ ]:
row_matrix = x.reshape(1, -1)

In [ ]:
row_matrix.shape

(1, 6)

In [ ]:
row_matrix

array([[7, 7, 2, 6, 3, 6]])

In [ ]:
col_matrix = x.reshape(-1, 1)
print(col_matrix)
print(col_matrix.shape)

[[7]
 [7]
 [2]
 [6]
 [3]
 [6]]
(6, 1)


In [ ]:
matrix = np.array([[4, 5], [5, 6]])

In [ ]:
matrix

array([[4, 5],
       [5, 6]])

In [ ]:
matrix.T

array([[4, 5],
       [5, 6]])

In [ ]:
matrix = np.array([[4, 5, 7], [5, 6, 2]])

In [ ]:
matrix

array([[4, 5, 7],
       [5, 6, 2]])

In [ ]:
matrix.T

array([[4, 5],
       [5, 6],
       [7, 2]])