In [4]:
import numpy as np

In [5]:
np.__version__

'1.23.5'

In [6]:
list = ["Home", "Alone"]
arr = np.array(list)
arr

array(['Home', 'Alone'], dtype='<U5')

In [7]:
type(arr)

numpy.ndarray

In [10]:
arr = np.array((3, 34, 23, 9, 3))
arr

array([ 3, 34, 23,  9,  3])

In [15]:
np.array([[[3, 23], [23, 32]], [34, 23], [23, 3]], dtype=object)

array([[list([3, 23]), list([23, 32])],
       [34, 23],
       [23, 3]], dtype=object)

In [16]:
np.array([32, 23, 23])

array([32, 23, 23])

In [20]:
np.array([[23, 23, True], [32, 23, "Home"]], dtype=object)

array([[23, 23, True],
       [32, 23, 'Home']], dtype=object)

In [21]:
np.array([32, 9, "Homecomming", True, 9.2])

array(['32', '9', 'Homecomming', 'True', '9.2'], dtype='<U32')

# Data science

How it install library in google collab
```python
    !pip install library_name
```

In [22]:
!pip install numpy

# Importing Numpy

In [23]:
import numpy as np

# Creating an empty array

In [25]:
x = np.array([])
type(x)

numpy.ndarray

In [26]:
x

array([], dtype=float64)

# Creating an array with even numbers

In [28]:
even = [2, 4, 6, 2, 98, 22]

In [29]:
even_array = np.array(even)

In [30]:
even_array

array([ 2,  4,  6,  2, 98, 22])

In [31]:
type(even_array)

numpy.ndarray

In [32]:
# nd means n-dimensional

In [34]:
even_array.ndim # ndim gives no of dimensions; this is 1 dimensional array

1

In [35]:
even_array.shape # (length_of_array, )

(6,)

In [36]:
len(even_array)

6

# Indexing and slicing

In [41]:
x = np.array([243, 232, 211, 454, 198, 399])

In [42]:
x

array([243, 232, 211, 454, 198, 399])

In [43]:
x[3]

454

In [44]:
x[-2]

198

In [45]:
x[2:5]

array([211, 454, 198])

In [48]:
x[2:-2] # slicing

array([211, 454])

In [49]:
x[:4]

array([243, 232, 211, 454])

In [50]:
x[-4:]

array([211, 454, 198, 399])

# Difference between list and array
* Array operation are faster than list operation which means array is faster then list
* List supports mutiple data types in contrast array support homogenous data type
* Array are memory effecient than list

# data type

In [54]:
l1 = [True, "hello", 55, 34.2]
type(l1[0])

bool

In [55]:
l1_array = np.array(l1)
l1_array

array(['True', 'hello', '55', '34.2'], dtype='<U32')

In [56]:
type(l1_array[0])

numpy.str_

# Random number generation

In [59]:
np.random.randint(1, 10)

4

In [65]:
np.random.seed(0)
np.random.randint(1, 10)

6

In [66]:
x_array = np.random.randint(low=1, high=10, size=50000)
x_array

array([1, 4, 4, ..., 9, 5, 2])

In [67]:
len(x_array)

50000

In [68]:
x_list = x_array.tolist() # typecasting array to list

In [69]:
type(x_list)

list

In [ ]:
x_list

In [77]:
%%time
sq = [item ** 2 for item in x_list] # list operation

CPU times: user 14.2 ms, sys: 0 ns, total: 14.2 ms
Wall time: 14.7 ms


In [76]:
%%time
sq = x_array ** 2 # array operation

CPU times: user 707 µs, sys: 0 ns, total: 707 µs
Wall time: 591 µs


# array is memory efficient

In [1]:
import numpy as np

In [7]:
even = np.array([95, 6, 2, 100], dtype = np.int8)
even

array([ 95,   6,   2, 100], dtype=int8)

In [8]:
even = np.array([95, 6, 2, 100], dtype = np.int16)
even

array([ 95,   6,   2, 100], dtype=int16)

# zeros(), ones() and empty()

In [9]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [10]:
np.ones(3, dtype=np.int8)

array([1, 1, 1], dtype=int8)

In [15]:
np.empty(15) # empty depends on memory

array([6.87632834e-310, 0.00000000e+000, 2.06917493e+161, 3.03387744e-152,
       2.31647114e-152, 1.01907795e+277, 9.77817447e+199, 1.39159278e-258,
       6.01347002e-154, 9.41558777e+165, 8.70446315e+183, 1.27967303e-152,
       6.24896858e-085, 6.87583831e-310, 8.69555537e-322])

In [16]:
# zeros and ones are used in binary image masking

# .arange()

In [18]:
np.arange(start=0, stop=5, step=1)

array([0, 1, 2, 3, 4])

In [19]:
list(range(0, 5, 1))

[0, 1, 2, 3, 4]

# .linspace()

In [26]:
np.linspace(start=0, stop=1, num=5) #0.25 is equal spacing

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [22]:
# zero dekhi one samma 5 number generate garne with equal spacing

# sort() and concatinate()

In [28]:
x = np.array([5, 0, -2, 6, 1, 9, 5])

In [33]:
np.sort(x) # ascendcing

array([-2,  0,  1,  5,  5,  6,  9])

In [34]:
np.flip(np.sort(x)) # descending

array([ 9,  6,  5,  5,  1,  0, -2])

In [35]:
x[::-1]

array([ 5,  9,  1,  6, -2,  0,  5])

In [49]:
x = np.array([5, 6])
y = np.array([1, 2, 3])

In [50]:
[5, 3] + [1, 2, 3] # you can concatinate list using + operator

[5, 3, 1, 2, 3]

In [51]:
x + y # array can't concatinate like this

ValueError: operands could not be broadcast together with shapes (2,) (3,) 

In [42]:
np.concatenate([x, y])

array([5, 6, 1, 2, 3])

# Vector operations and Broadcasting

In [63]:
# vector operations
x = np.array([8, 9])
y = np.array([2, 3])

In [54]:
x + y

array([10, 12])

In [55]:
x - y

array([6, 6])

In [56]:
x * y

array([16, 27])

In [57]:
x / y

array([4., 3.])

In [58]:
x % y

array([0, 0])

In [64]:
# broadcasting
x = np.array([8, 9])
y = np.array([2, 3])
2 * x
2 * y

array([4, 6])

In [65]:
3 + x

array([11, 12])

In [66]:
3 - y

array([1, 0])

In [68]:
5 - x

array([-3, -4])

# .any() vs .all()

In [79]:
np.random.seed()
x = np.random.randint(1, 7, 10) # low, high, size
x

array([4, 5, 2, 1, 6, 5, 5, 1, 3, 1])

In [80]:
x >= 5

array([False,  True, False, False,  True,  True,  True, False, False,
       False])

In [81]:
np.any(x>=5) # kunai 5 vanda thulo xa vane True aauxa

True

In [83]:
np.all(x>=5) # sabai 5 vanda thulo vayo vane True natra False

False

In [86]:
np.all(x>=5)

False

In [87]:
x[x>=5]

array([5, 6, 5, 5])

In [ ]:
x[x==1 or x==6] # logical operator numpy ma use garna paudaina

# numpy works in bitwise operator

In [91]:
x[(x==1) | (x==6)] # bitwise or

array([1, 6, 1, 1])

In [94]:
x[(x > 2) & (x < 6)] # bitwise and

array([4, 5, 5, 5, 3])

# statistics using numpy

In [96]:
np.random.seed(0)
x = np.random.randint(1, 100, size=50)
x

array([45, 48, 65, 68, 68, 10, 84, 22, 37, 88, 71, 89, 89, 13, 59, 66, 40,
       88, 47, 89, 82, 38, 26, 78, 73, 10, 21, 81, 70, 80, 48, 65, 83, 89,
       50, 30, 20, 20, 15, 40, 33, 66, 10, 58, 33, 32, 75, 24, 36, 76])

In [97]:
np.mean(x)

52.96

In [98]:
x.mean()

52.96

In [99]:
np.median(x)

54.0

In [105]:
np.var(x) # variance

659.9584

In [106]:
np.std(x) # standard deviation

25.689655505669982

In [107]:
np.min(x)

10

In [108]:
np.max(x)

89

In [109]:
from scipy.stats import mode
mode(x)

ModeResult(mode=89, count=4)